stringData:
    IAMBARN_ADMIN_TOKEN: ENC[AES256_GCM,data:G7dJy/BntjKeVxyljaEMxP+9QkC5U3GDKS5Iw4aeUHtVq0rioGNXSvyzwBQOWubHrvQ=,iv:HFiMgzJSUoJFOV06LcoaKt2+1TpTORsm0YPzYJCu9uE=,tag:TKy+mwsqb77YUxZgYlFU6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NmdmSWpQQm1yT1pRODNq
            bGNVWjlNb1pucFFkRXZPN0xRVzdyNE9rR3dRCnpHbldnRGxkZ2FpV3pwVGdZem5R
            ZDdtNkZwT3lhWHFRMGhxTzFteG9hWk0KLS0tIDdnM1dTOFkyeVpwTzQzZURWYS9R
            QmpMQ21XYlQyYnNTVkQ4UnN1ZVVmS1EKZHe13IxPZdRg1BnUI8kF/Ce/Xu1P3Hl/
            hAM5P8GRbsIKzzsvqeK6LGi9Cn0xEASzqd8tjwKxWwn2bWci/MiwlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-09-21T11:51:34Z"
    mac: ENC[AES256_GCM,data:uVKLj3gFrBAI6Zaiqz3YEo7m+uYtJvkDwFlkPflZ1wz/pQDQay47ObY/9BoDhr65u5NvEeQ5b0Yn3EYIK5czI/w0F/fDM0Y8jND3x0eJQC8NhkhUTjWxhMJtH+alg3x7IjgGdVI4pYg3rdBhZumfaYdul+33KQsVikpF7Kfh0B8=,iv:IYEyCI2xKTW0LMHQm32UpcxyXyxfuvN4k183LAndO4I=,tag:NqBspx3DotZ/ipJk4+r1PQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
