stringData:
    IAMBARN_ADMIN_TOKEN: ENC[AES256_GCM,data:wmgOINaTsTlHSaUhaz/kk1itOnmP8B8KP2Y6DmpSjoV8boEtIrIt9565ibz/KJyVRN4=,iv:Gi4K2je+U0pRnDVe2owjM1uZtRwU0seF0wqvHk82RdU=,tag:DnnP2T9+PM7A741It140QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVmpYcmRickp3Q3g2Umpy
            UmZxSWFqNE8wWWNvTHlBQldNYlkzYllsb3hZCmIrWUttTkF2cExDRCtrL24xM3ps
            dWFRT25YcEhWNVYvdWpYK1lOVWUydmsKLS0tIHRjZVNNL3pHM3FWVERRTDMrMFdq
            MHdjRG5ZcnNGaFkralBDbkVkQzJhTXcKClkXlQJUo+xNLq0ISJSU5TUFm8+oUOLR
            g8CxkJDLex3VaHPMuJZnMoj9tyLTYHMSiU8Q/yOZRmcFQB0b83S6cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-09-21T11:51:34Z"
    mac: ENC[AES256_GCM,data:GrbbwNjeJTYpNtc+1xuvR24nDO97OETr0cDoWDZxUyvWmNp/pmY8Sg5COf/TQxOlEzZ0jvqrfVInVZtvmjAXAl1jmIGHZtCJX07qiw9aulzev5bshmp68D+bh49vmGCZxDkubt1/DgIJhIG3vVFboCHW4zknFeWhqBOw51BNPCc=,iv:VSfdJI/AHvi+nJDrxMq7Uwz6OiM9o/ugMv5LWpkDy9g=,tag:2xjoFfSxxmXunOY0Y7Hqew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
