apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funnelbarn
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: funnelbarn.staging.wiebe.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: funnelbarn
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: funnelbarn-web
                port:
                  name: http
  tls:
    - hosts:
        - funnelbarn.staging.wiebe.xyz
