apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trailpost-staging
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - web-deployment.yaml
  - service.yaml
  - web-service.yaml
  - ingress.yaml
images:
  - name: trailpost/service
    newName: ghcr.io/webwiebe/trailpost/service
    newTag: local
  - name: trailpost/web
    newName: ghcr.io/webwiebe/trailpost/web
    newTag: local
