apiVersion: v1
kind: Service
metadata:
  name: funnelbarn-web
spec:
  selector:
    app.kubernetes.io/name: funnelbarn-web
    app.kubernetes.io/environment: staging
  ports:
    - name: http
      port: 3000
      targetPort: http
