apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trailpost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: analytics.wiebe.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: trailpost
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trailpost-web
                port:
                  name: http
  tls:
    - hosts:
        - analytics.wiebe.xyz
      secretName: analytics-wiebe-xyz-tls
