apiVersion: v1
kind: Service
metadata:
  name: trailpost
spec:
  selector:
    app.kubernetes.io/name: trailpost
    app.kubernetes.io/environment: production
  ports:
    - name: http
      port: 8080
      targetPort: http
