apiVersion: apps/v1
kind: Deployment
metadata:
  name: funnelbarn-web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: funnelbarn-web
      app.kubernetes.io/environment: production
  template:
    metadata:
      labels:
        app.kubernetes.io/name: funnelbarn-web
        app.kubernetes.io/environment: production
    spec:
      nodeSelector:
        kubernetes.io/hostname: layer7-prod
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: funnelbarn-web
          image: funnelbarn/web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
