apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funnelbarn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: funnelbarn-testing.wiebe.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: funnelbarn
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: funnelbarn-web
                port:
                  name: http
  tls:
    - hosts:
        - funnelbarn-testing.wiebe.xyz
      secretName: funnelbarn-testing-wiebe-xyz-tls
