apiVersion: v1
kind: Service
metadata:
  name: trailpost-web
spec:
  selector:
    app.kubernetes.io/name: trailpost-web
    app.kubernetes.io/environment: testing
  ports:
    - name: http
      port: 3000
      targetPort: http
