// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abtests.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getABTestByID = `-- name: GetABTestByID :one
SELECT id, project_id, name, status, control_filter, variant_filter, conversion_event, created_at
FROM ab_tests WHERE id = ?
`

func (q *Queries) GetABTestByID(ctx context.Context, id string) (AbTest, error) {
	row := q.db.QueryRowContext(ctx, getABTestByID, id)
	var i AbTest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.ControlFilter,
		&i.VariantFilter,
		&i.ConversionEvent,
		&i.CreatedAt,
	)
	return i, err
}

const insertABTest = `-- name: InsertABTest :exec
INSERT INTO ab_tests (id, project_id, name, status, control_filter, variant_filter, conversion_event)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertABTestParams struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	Status          string         `json:"status"`
	ControlFilter   sql.NullString `json:"control_filter"`
	VariantFilter   sql.NullString `json:"variant_filter"`
	ConversionEvent string         `json:"conversion_event"`
}

func (q *Queries) InsertABTest(ctx context.Context, arg InsertABTestParams) error {
	_, err := q.db.ExecContext(ctx, insertABTest,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Status,
		arg.ControlFilter,
		arg.VariantFilter,
		arg.ConversionEvent,
	)
	return err
}

const listABTests = `-- name: ListABTests :many
SELECT id, project_id, name, status, control_filter, variant_filter, conversion_event, created_at
FROM ab_tests WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListABTests(ctx context.Context, projectID string) ([]AbTest, error) {
	rows, err := q.db.QueryContext(ctx, listABTests, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbTest
	for rows.Next() {
		var i AbTest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Status,
			&i.ControlFilter,
			&i.VariantFilter,
			&i.ConversionEvent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
