// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package sqlcgen

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, project_id, name, key_hash, scope)
VALUES (?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	Scope     string `json:"scope"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.KeyHash,
		arg.Scope,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const ensureSetupAPIKey = `-- name: EnsureSetupAPIKey :exec
INSERT INTO api_keys (id, project_id, name, key_hash, scope)
VALUES (?, ?, 'setup', ?, 'ingest')
ON CONFLICT(key_hash) DO NOTHING
`

type EnsureSetupAPIKeyParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	KeyHash   string `json:"key_hash"`
}

func (q *Queries) EnsureSetupAPIKey(ctx context.Context, arg EnsureSetupAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, ensureSetupAPIKey, arg.ID, arg.ProjectID, arg.KeyHash)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, project_id, name, key_hash, scope, last_used_at, created_at
FROM api_keys WHERE id = ?
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.Scope,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, project_id, name, key_hash, scope, last_used_at, created_at
FROM api_keys WHERE project_id = ? ORDER BY created_at
`

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyHash,
			&i.Scope,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAPIKeys = `-- name: ListAllAPIKeys :many
SELECT id, project_id, name, key_hash, scope, last_used_at, created_at
FROM api_keys ORDER BY created_at
`

func (q *Queries) ListAllAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAllAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyHash,
			&i.Scope,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAPIKeyBySHA256 = `-- name: LookupAPIKeyBySHA256 :one
SELECT project_id, scope FROM api_keys
WHERE key_hash = ? LIMIT 1
`

type LookupAPIKeyBySHA256Row struct {
	ProjectID string `json:"project_id"`
	Scope     string `json:"scope"`
}

func (q *Queries) LookupAPIKeyBySHA256(ctx context.Context, keyHash string) (LookupAPIKeyBySHA256Row, error) {
	row := q.db.QueryRowContext(ctx, lookupAPIKeyBySHA256, keyHash)
	var i LookupAPIKeyBySHA256Row
	err := row.Scan(&i.ProjectID, &i.Scope)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE key_hash = ?
`

func (q *Queries) TouchAPIKey(ctx context.Context, keyHash string) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, keyHash)
	return err
}
