// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getEventByIngestID = `-- name: GetEventByIngestID :one
SELECT id FROM events WHERE ingest_id = ? LIMIT 1
`

func (q *Queries) GetEventByIngestID(ctx context.Context, ingestID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventByIngestID, ingestID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, project_id, session_id, user_id_hash, name, url, referrer, referrer_domain,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    properties, user_agent, browser, os, device_type, country_code,
    ingest_id, occurred_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	SessionID      string         `json:"session_id"`
	UserIDHash     sql.NullString `json:"user_id_hash"`
	Name           string         `json:"name"`
	Url            sql.NullString `json:"url"`
	Referrer       sql.NullString `json:"referrer"`
	ReferrerDomain sql.NullString `json:"referrer_domain"`
	UtmSource      sql.NullString `json:"utm_source"`
	UtmMedium      sql.NullString `json:"utm_medium"`
	UtmCampaign    sql.NullString `json:"utm_campaign"`
	UtmTerm        sql.NullString `json:"utm_term"`
	UtmContent     sql.NullString `json:"utm_content"`
	Properties     sql.NullString `json:"properties"`
	UserAgent      sql.NullString `json:"user_agent"`
	Browser        sql.NullString `json:"browser"`
	Os             sql.NullString `json:"os"`
	DeviceType     sql.NullString `json:"device_type"`
	CountryCode    sql.NullString `json:"country_code"`
	IngestID       string         `json:"ingest_id"`
	OccurredAt     time.Time      `json:"occurred_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.UserIDHash,
		arg.Name,
		arg.Url,
		arg.Referrer,
		arg.ReferrerDomain,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.Properties,
		arg.UserAgent,
		arg.Browser,
		arg.Os,
		arg.DeviceType,
		arg.CountryCode,
		arg.IngestID,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, project_id, session_id, user_id_hash, name, url, referrer, referrer_domain,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    properties, user_agent, browser, os, device_type, country_code,
    ingest_id, occurred_at, created_at
FROM events WHERE project_id = ? ORDER BY occurred_at DESC LIMIT ? OFFSET ?
`

type ListEventsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.UserIDHash,
			&i.Name,
			&i.Url,
			&i.Referrer,
			&i.ReferrerDomain,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmTerm,
			&i.UtmContent,
			&i.Properties,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.DeviceType,
			&i.CountryCode,
			&i.IngestID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
