// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: funnels.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteFunnel = `-- name: DeleteFunnel :exec
DELETE FROM funnels WHERE id = ?
`

func (q *Queries) DeleteFunnel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFunnel, id)
	return err
}

const deleteFunnelSteps = `-- name: DeleteFunnelSteps :exec
DELETE FROM funnel_steps WHERE funnel_id = ?
`

func (q *Queries) DeleteFunnelSteps(ctx context.Context, funnelID string) error {
	_, err := q.db.ExecContext(ctx, deleteFunnelSteps, funnelID)
	return err
}

const getFunnelByID = `-- name: GetFunnelByID :one
SELECT id, project_id, name, COALESCE(description, '') AS description, created_at
FROM funnels WHERE id = ?
`

type GetFunnelByIDRow struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetFunnelByID(ctx context.Context, id string) (GetFunnelByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFunnelByID, id)
	var i GetFunnelByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertFunnel = `-- name: InsertFunnel :exec
INSERT INTO funnels (id, project_id, name, description) VALUES (?, ?, ?, ?)
`

type InsertFunnelParams struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) InsertFunnel(ctx context.Context, arg InsertFunnelParams) error {
	_, err := q.db.ExecContext(ctx, insertFunnel,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
	)
	return err
}

const insertFunnelStep = `-- name: InsertFunnelStep :exec
INSERT INTO funnel_steps (id, funnel_id, step_order, event_name, filters)
VALUES (?, ?, ?, ?, ?)
`

type InsertFunnelStepParams struct {
	ID        string         `json:"id"`
	FunnelID  string         `json:"funnel_id"`
	StepOrder int64          `json:"step_order"`
	EventName string         `json:"event_name"`
	Filters   sql.NullString `json:"filters"`
}

func (q *Queries) InsertFunnelStep(ctx context.Context, arg InsertFunnelStepParams) error {
	_, err := q.db.ExecContext(ctx, insertFunnelStep,
		arg.ID,
		arg.FunnelID,
		arg.StepOrder,
		arg.EventName,
		arg.Filters,
	)
	return err
}

const listFunnelSteps = `-- name: ListFunnelSteps :many
SELECT id, funnel_id, step_order, event_name, COALESCE(filters, '[]') AS filters
FROM funnel_steps WHERE funnel_id = ? ORDER BY step_order
`

type ListFunnelStepsRow struct {
	ID        string `json:"id"`
	FunnelID  string `json:"funnel_id"`
	StepOrder int64  `json:"step_order"`
	EventName string `json:"event_name"`
	Filters   string `json:"filters"`
}

func (q *Queries) ListFunnelSteps(ctx context.Context, funnelID string) ([]ListFunnelStepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFunnelSteps, funnelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFunnelStepsRow
	for rows.Next() {
		var i ListFunnelStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.FunnelID,
			&i.StepOrder,
			&i.EventName,
			&i.Filters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunnels = `-- name: ListFunnels :many
SELECT id, project_id, name, COALESCE(description, '') AS description, created_at
FROM funnels WHERE project_id = ? ORDER BY created_at
`

type ListFunnelsRow struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListFunnels(ctx context.Context, projectID string) ([]ListFunnelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFunnels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFunnelsRow
	for rows.Next() {
		var i ListFunnelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunnelMeta = `-- name: UpdateFunnelMeta :exec
UPDATE funnels SET name = ?, description = ? WHERE id = ?
`

type UpdateFunnelMetaParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateFunnelMeta(ctx context.Context, arg UpdateFunnelMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateFunnelMeta, arg.Name, arg.Description, arg.ID)
	return err
}
