// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type AbTest struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	Status          string         `json:"status"`
	ControlFilter   sql.NullString `json:"control_filter"`
	VariantFilter   sql.NullString `json:"variant_filter"`
	ConversionEvent string         `json:"conversion_event"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ApiKey struct {
	ID         string       `json:"id"`
	ProjectID  string       `json:"project_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Scope      string       `json:"scope"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Event struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	SessionID      string         `json:"session_id"`
	UserIDHash     sql.NullString `json:"user_id_hash"`
	Name           string         `json:"name"`
	Url            sql.NullString `json:"url"`
	Referrer       sql.NullString `json:"referrer"`
	ReferrerDomain sql.NullString `json:"referrer_domain"`
	UtmSource      sql.NullString `json:"utm_source"`
	UtmMedium      sql.NullString `json:"utm_medium"`
	UtmCampaign    sql.NullString `json:"utm_campaign"`
	UtmTerm        sql.NullString `json:"utm_term"`
	UtmContent     sql.NullString `json:"utm_content"`
	Properties     sql.NullString `json:"properties"`
	UserAgent      sql.NullString `json:"user_agent"`
	Browser        sql.NullString `json:"browser"`
	Os             sql.NullString `json:"os"`
	DeviceType     sql.NullString `json:"device_type"`
	CountryCode    sql.NullString `json:"country_code"`
	IngestID       string         `json:"ingest_id"`
	OccurredAt     time.Time      `json:"occurred_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Funnel struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type FunnelStep struct {
	ID        string         `json:"id"`
	FunnelID  string         `json:"funnel_id"`
	StepOrder int64          `json:"step_order"`
	EventName string         `json:"event_name"`
	Filters   sql.NullString `json:"filters"`
}

type Project struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
}

type Session struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	FirstSeenAt time.Time      `json:"first_seen_at"`
	LastSeenAt  time.Time      `json:"last_seen_at"`
	EventCount  int64          `json:"event_count"`
	EntryUrl    sql.NullString `json:"entry_url"`
	ExitUrl     sql.NullString `json:"exit_url"`
	Referrer    sql.NullString `json:"referrer"`
	UtmSource   sql.NullString `json:"utm_source"`
	UtmMedium   sql.NullString `json:"utm_medium"`
	UtmCampaign sql.NullString `json:"utm_campaign"`
	DeviceType  sql.NullString `json:"device_type"`
	CountryCode sql.NullString `json:"country_code"`
}

type SessionsHttp struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
