// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const approveProject = `-- name: ApproveProject :exec
UPDATE projects SET status = 'active' WHERE id = ?
`

func (q *Queries) ApproveProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, approveProject, id)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, slug, status, domain, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, status, domain, created_at FROM projects WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (id, name, slug) VALUES (?, ?, ?)
`

type InsertProjectParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertProject, arg.ID, arg.Name, arg.Slug)
	return err
}

const insertProjectPending = `-- name: InsertProjectPending :exec
INSERT INTO projects (id, name, slug, status) VALUES (?, ?, ?, 'pending')
`

type InsertProjectPendingParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertProjectPending(ctx context.Context, arg InsertProjectPendingParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectPending, arg.ID, arg.Name, arg.Slug)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, status, domain, created_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = ?, domain = ? WHERE id = ?
`

type UpdateProjectParams struct {
	Name   string         `json:"name"`
	Domain sql.NullString `json:"domain"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject, arg.Name, arg.Domain, arg.ID)
	return err
}

const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects SET name = ? WHERE id = ?
`

type UpdateProjectNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectName, arg.Name, arg.ID)
	return err
}
