// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_health.sql

package sqlcgen

import (
	"context"
)

const getProjectHealth = `-- name: GetProjectHealth :one
SELECT project_id, setup_called, events_received, flags_evaluated, recordings_received, updated_at
FROM project_health
WHERE project_id = ?
`

func (q *Queries) GetProjectHealth(ctx context.Context, projectID string) (ProjectHealth, error) {
	row := q.db.QueryRowContext(ctx, getProjectHealth, projectID)
	var i ProjectHealth
	err := row.Scan(
		&i.ProjectID,
		&i.SetupCalled,
		&i.EventsReceived,
		&i.FlagsEvaluated,
		&i.RecordingsReceived,
		&i.UpdatedAt,
	)
	return i, err
}

const markProjectHealthEventsReceived = `-- name: MarkProjectHealthEventsReceived :exec
INSERT INTO project_health (project_id, events_received, updated_at)
VALUES (?, 1, CURRENT_TIMESTAMP)
ON CONFLICT(project_id) DO UPDATE SET
    events_received = 1,
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkProjectHealthEventsReceived(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, markProjectHealthEventsReceived, projectID)
	return err
}

const markProjectHealthFlagsEvaluated = `-- name: MarkProjectHealthFlagsEvaluated :exec
INSERT INTO project_health (project_id, flags_evaluated, updated_at)
VALUES (?, 1, CURRENT_TIMESTAMP)
ON CONFLICT(project_id) DO UPDATE SET
    flags_evaluated = 1,
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkProjectHealthFlagsEvaluated(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, markProjectHealthFlagsEvaluated, projectID)
	return err
}

const markProjectHealthRecordingsReceived = `-- name: MarkProjectHealthRecordingsReceived :exec
INSERT INTO project_health (project_id, recordings_received, updated_at)
VALUES (?, 1, CURRENT_TIMESTAMP)
ON CONFLICT(project_id) DO UPDATE SET
    recordings_received = 1,
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkProjectHealthRecordingsReceived(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, markProjectHealthRecordingsReceived, projectID)
	return err
}

const markProjectHealthSetupCalled = `-- name: MarkProjectHealthSetupCalled :exec
INSERT INTO project_health (project_id, setup_called, updated_at)
VALUES (?, 1, CURRENT_TIMESTAMP)
ON CONFLICT(project_id) DO UPDATE SET
    setup_called = 1,
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkProjectHealthSetupCalled(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, markProjectHealthSetupCalled, projectID)
	return err
}

const resetProjectHealth = `-- name: ResetProjectHealth :exec
UPDATE project_health
SET setup_called = 0,
    events_received = 0,
    flags_evaluated = 0,
    recordings_received = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE project_id = ?
`

func (q *Queries) ResetProjectHealth(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, resetProjectHealth, projectID)
	return err
}
