// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
)

const approveProject = `-- name: ApproveProject :exec
UPDATE projects SET status = 'active' WHERE id = ?
`

func (q *Queries) ApproveProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, approveProject, id)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, slug) VALUES (?, ?, ?)
`

type CreateProjectParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject, arg.ID, arg.Name, arg.Slug)
	return err
}

const createProjectPending = `-- name: CreateProjectPending :exec
INSERT INTO projects (id, name, slug, status) VALUES (?, ?, ?, 'pending')
`

type CreateProjectPendingParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateProjectPending(ctx context.Context, arg CreateProjectPendingParams) error {
	_, err := q.db.ExecContext(ctx, createProjectPending, arg.ID, arg.Name, arg.Slug)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, slug, status, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, status, created_at FROM projects WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const hasProjects = `-- name: HasProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) HasProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, status, created_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects SET name = ? WHERE id = ?
`

type UpdateProjectNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectName, arg.Name, arg.ID)
	return err
}
