// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, project_id, first_seen_at, last_seen_at, event_count,
       entry_url, exit_url, referrer, utm_source, utm_medium, utm_campaign,
       device_type, country_code
FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.EventCount,
		&i.EntryUrl,
		&i.ExitUrl,
		&i.Referrer,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.DeviceType,
		&i.CountryCode,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, project_id, first_seen_at, last_seen_at, event_count,
    entry_url, exit_url, referrer, utm_source, utm_medium, utm_campaign,
    device_type, country_code)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	FirstSeenAt time.Time      `json:"first_seen_at"`
	LastSeenAt  time.Time      `json:"last_seen_at"`
	EventCount  int64          `json:"event_count"`
	EntryUrl    sql.NullString `json:"entry_url"`
	ExitUrl     sql.NullString `json:"exit_url"`
	Referrer    sql.NullString `json:"referrer"`
	UtmSource   sql.NullString `json:"utm_source"`
	UtmMedium   sql.NullString `json:"utm_medium"`
	UtmCampaign sql.NullString `json:"utm_campaign"`
	DeviceType  sql.NullString `json:"device_type"`
	CountryCode sql.NullString `json:"country_code"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.ProjectID,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.EventCount,
		arg.EntryUrl,
		arg.ExitUrl,
		arg.Referrer,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.DeviceType,
		arg.CountryCode,
	)
	return err
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_id, first_seen_at, last_seen_at, event_count,
       entry_url, exit_url, referrer, utm_source, utm_medium, utm_campaign,
       device_type, country_code
FROM sessions WHERE project_id = ? ORDER BY last_seen_at DESC LIMIT ? OFFSET ?
`

type ListSessionsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.EventCount,
			&i.EntryUrl,
			&i.ExitUrl,
			&i.Referrer,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.DeviceType,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions SET last_seen_at = ?, event_count = ?, exit_url = ? WHERE id = ?
`

type UpdateSessionParams struct {
	LastSeenAt time.Time      `json:"last_seen_at"`
	EventCount int64          `json:"event_count"`
	ExitUrl    sql.NullString `json:"exit_url"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.LastSeenAt,
		arg.EventCount,
		arg.ExitUrl,
		arg.ID,
	)
	return err
}
